# Generated by Django 3.2.6 on 2023-03-27 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuisine_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentsPlace',
            fields=[
                ('entertainments_place_id', models.AutoField(primary_key=True, serialize=False)),
                ('entertainments_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('events_id', models.AutoField(primary_key=True, serialize=False)),
                ('events_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('price_range', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPlaceCategory',
            fields=[
                ('food_place_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPlaces',
            fields=[
                ('food_place_id', models.AutoField(primary_key=True, serialize=False)),
                ('average_check', models.FloatField()),
                ('place_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cuisine')),
                ('food_place_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.foodplacecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('tours_id', models.AutoField(primary_key=True, serialize=False)),
                ('tours_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('collection_time', models.TimeField()),
                ('check_out', models.TimeField()),
                ('place_collection', models.CharField(max_length=200)),
                ('arrival_time', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ToursImage',
            fields=[
                ('tours_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=200)),
                ('tours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tours')),
            ],
        ),
        migrations.CreateModel(
            name='TourSchedule',
            fields=[
                ('tour_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_item', models.CharField(max_length=50)),
                ('schedule_item_description', models.CharField(max_length=100)),
                ('schedule_item_order', models.IntegerField()),
                ('tours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tours')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_item', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('food_places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.foodplaces')),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentsEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entertainments_event_name', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('reserve_date', models.DateField()),
                ('hall', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('entertainment_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.entertainmentsplace')),
            ],
        ),
    ]
