# Generated by Django 3.2.6 on 2023-03-29 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentsevent',
            name='image',
            field=models.ImageField(upload_to='entertainments-event-image/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to='events-image/'),
        ),
        migrations.AlterField(
            model_name='toursimage',
            name='image',
            field=models.ImageField(upload_to='tours-image/'),
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('table_number', models.IntegerField()),
                ('seating_capacity', models.IntegerField()),
                ('is_available', models.BooleanField()),
                ('food_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.foodplaces')),
            ],
            options={
                'db_table': 'restaurant_tables',
            },
        ),
    ]
