# Generated by Django 3.2.6 on 2023-03-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20230329_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restauranttable',
            old_name='seating_capacity',
            new_name='table_capacity',
        ),
        migrations.RemoveField(
            model_name='restauranttable',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='restauranttable',
            name='name',
        ),
        migrations.RemoveField(
            model_name='restauranttable',
            name='table_number',
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='height',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='hover_color',
            field=models.CharField(default='blue', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='shape',
            field=models.CharField(default='rectangle', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='table_name',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='width',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='x',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='y',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='restauranttable',
            table=None,
        ),
    ]
