# Generated by Django 3.2.6 on 2023-03-30 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_entertainmentplacecategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainmentsplace',
            name='entertainment_place_category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.entertainmentplacecategories'),
            preserve_default=False,
        ),
    ]
