# Generated by Django 3.2.6 on 2023-03-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_entertainmentsplace_entertainment_place_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entertainmentsplace',
            old_name='entertainment_place_category_id',
            new_name='entertainment_place_category',
        ),
    ]
