# Generated by Django 3.2.6 on 2023-03-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_entertainment_place_category_id_entertainmentsplace_entertainment_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplaces',
            name='image',
            field=models.ImageField(default='test.jpg', upload_to='food-place-image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='test.jpg', upload_to='menu-image/'),
            preserve_default=False,
        ),
    ]
