# Generated by Django 3.2.6 on 2023-04-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_foodplaces_reservable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodplaces',
            name='reservable',
        ),
    ]
