# Generated by Django 3.2.6 on 2023-04-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_foodplaces_reservable'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplacecategory',
            name='reservable',
            field=models.BooleanField(default=False),
        ),
    ]
