# Generated by Django 3.2.6 on 2023-04-25 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_foodplacecategory_reservable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('menu_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.menu')),
            ],
        ),
    ]
